name: CI/CD - Build JAR and Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: application.yml 파일 만들기
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: build.gradle 생성
        run: echo "${{ secrets.BUILD_GRADLE }}" | base64 --decode > build.gradle

      - name: settings.gradle 생성
        run: echo "${{ secrets.SETTINGS_GRADLE }}" | base64 --decode > settings.gradle

      - name: keystore.p12 파일 복원
        run: echo "${{ secrets.KEYSTORE_P12_BASE64 }}" | base64 --decode > ./src/main/resources/keystore.p12

      - name: gradlew 실행 권한 주기
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: EC2 디렉토리 준비
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/yogiattacku-back/tobe

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/yogiattacku-back/tobe

      - name: SSH and depoly on EC2
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            
            cd ~/yogiattacku-back
            
            sudo docker compose down || true
            sudo docker compose up -d
            
            sudo rm -rf /home/ubuntu/yogiattacku-back/current
            sudo mkdir /home/ubuntu/yogiattacku-back/current
            sudo mv /home/ubuntu/yogiattacku-back/tobe/project.jar /home/ubuntu/yogiattacku-back/current
            sudo fuser -k -n tcp 443 || true
            
            cd /home/ubuntu/yogiattacku-back/current
            sudo nohup java -jar project.jar 2>&1 &
            sudo rm -rf /home/ubuntu/yogiattacku-back/tobe

